### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/pedrosilva/.atom/packages/sync-se...

### ISSUE THREAD

**Issue by pedro93** [Hackafe/atom-sync-settings#208] opened 2016-03-08 12:02 UTC
[Enter steps to reproduce below:]

Merely updating to new version

1. Go to settings
2. Updates
3. Select update atom-sync

**Atom Version**: 1.5.4
**System**: Mac OS X 10.10.5
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.7.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/pedrosilva/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/pedrosilva/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/Users/pedrosilva/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/Users/pedrosilva/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/Users/pedrosilva/.atom/packages/sync-settings/lib/sync-settings.coffee:198:18)
    at Object.SyncSettings.checkForUpdate (/Users/pedrosilva/.atom/packages/sync-settings/lib/sync-settings.coffee:46:8)
    at Immediate._onImmediate (/Users/pedrosilva/.atom/packages/sync-settings/lib/sync-settings.coffee:32:8)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
     -9:46.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -8:27.9.0 core:select-all (atom-text-editor.editor.is-focused)
     -8:27.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -8:25.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -8:25.2.0 prettify:prettify (atom-text-editor.editor)
     -8:18.9.0 core:save (atom-text-editor.editor.is-focused)
     -1:21.7.0 command-palette:toggle (ol.tree-view.list-tree.has-collapsable-children.focusable-panel.full-menu)
  9x -1:19.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:18.1.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:18.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:13.5.0 settings-view:check-for-package-updates (atom-workspace.workspace.theme-atom-dark-syntax.theme-atom-dark-ui.scrollbars-visible-when-scrolling)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "double-click-tree-view",
      "metrics",
      "wrap-guide"
    ],
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [
      "tree-view"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "333e3632-6d1c-48b4-89e2-8c23c32219d6",
    "_lastBackupHash": "0ed6e83ef7bd827a678c45a155ad7ca4fb17829d",
    "gistId": "e9795606b47f703cf6cd",
    "personalAccessToken": "026eabed588fae1f93a6efff789deebd95eada14"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.26
atom-pair, v2.0.10
atom-prettify, v0.1.3
auto-indent, v0.5.0
autohide-tree-view, v0.25.1
build, v0.55.0
build-gulp, v0.7.0
emmet, v2.4.2
language-latex, v0.6.1
linter, v1.11.3
pane-split-moves-tab, v0.0.3
pdf-view, v0.48.0
project-manager, v2.7.6
sync-settings, v0.7.0
tab-close-double-click, v2.0.2
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by jerone** [comment] 2016-03-08 12:27
Duplicate of https://github.com/Hackafe/atom-sync-settings/issues/194.

In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Closed by jerone** 2016-03-08 12:27 UTC

**Comment by pedro93** [comment] 2016-03-08 12:30
I did it as soon as I created the issue, thank you for the concern though :).
