### ISSUE TITLE
Uncaught SyntaxError: Unexpected token u

### ISSUE THREAD

**Issue by crperlin** [Hackafe/atom-sync-settings#131] opened 2015-09-24 17:23 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.16
**System**: Unknown Windows Version
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.6.0

### Stack Trace

Uncaught SyntaxError: Unexpected token u

```
At file:///C:/Users/CRPER/AppData/Local/atom/app-1.0.16/resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22atom%3A%2F%2F.atom%2Fconfig%22%2C%22initialLine%22%3Anull%2C%22initialColumn%22%3Anull%7D%5D%2C%22bootstrapScript%22%3A%22C%3A%5C%5CUsers%5C%5CCRPER%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Capp-1.0.16%5C%5Cresources%5C%5Capp.asar%5C%5Csrc%5C%5Cwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22C%3A%5C%5CUsers%5C%5CCRPER%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Capp-1.0.16%5C%5Cresources%5C%5Capp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%221.0.16%22%2C%22shellLoadTime%22%3A283%2C%22initialPaths%22%3A%5B%22atom%3A%2F%2F.atom%2Fconfig%22%5D%7D:12

SyntaxError: Unexpected token u
  at Object.parse (native)
  at C:\Users\CRPER\.atom\packages\sync-settings\lib\sync-settings.coffee:168:37
  at C:\Users\CRPER\.atom\packages\sync-settings\node_modules\github\api\v3.0.0\gists.js:342:17
  at callCallback (C:\Users\CRPER\.atom\packages\sync-settings\node_modules\github\index.js:743:17)
  at IncomingMessage.<anonymous> (C:\Users\CRPER\.atom\packages\sync-settings\node_modules\github\index.js:796:25)
  at emitNone (events.js:72:20)
  at IncomingMessage.emit (events.js:166:7)
  at endReadableNT (_stream_readable.js:889:12)
  at doNTCallback2 (node.js:438:9)
  at process._tickCallback (node.js:352:17)

```

### Commands

```
     -0:09.0 sync-settings:restore (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "sync-settings": {
    "_analyticsUserId": "b01c5ba0-ff32-40e3-866a-3d86fa47c89a",
    "personalAccessToken": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "gistId": "d34b6a9ad20455b0bde7"
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.1
atom-html-preview, v0.1.11
atom-shortcuts, v0.0.2
autoclose-html, v0.19.0
autocomplete-html-entities, v0.1.0
autocomplete-modules, v1.1.0
bottom-dock, v0.3.5
color-picker, v2.0.12
css-snippets, v0.9.0
docblockr, v0.7.3
emmet, v2.3.12
file-icons, v1.6.9
flex-tool-bar, v0.5.0
foldername-tabs, v0.1.5
fonts, v0.6.0
git-log, v0.4.1
gulp-manager, v0.2.10
gulp-snippets, v0.6.2
highlight-selected, v0.10.1
javascript-snippets, v1.0.0
jquery-snippets, v11.0.0
jsformat, v0.9.0
linter, v1.6.0
linter-js-standard, v3.2.0
linter-jshint, v1.2.0
linter-less, v2.1.0
linter-scss-lint, v2.0.0
minimap, v4.13.3
minimap-find-and-replace, v4.3.0
minimap-pigments, v0.1.6
pdf-view, v0.27.0
pigments, v0.15.0
react, v0.12.10
script-runner, v1.8.4
Sublime-Style-Column-Selection, v1.3.0
sync-settings, v0.6.0
tool-bar, v0.1.9
tool-bar-main, v0.0.8
tree-view-git-status, v0.2.1
vim-mode, v0.60.0
vim-mode-visual-block, v0.2.13

# Dev
No dev packages
```

**Comment by dirk-thomas** [comment] 2016-01-13 17:13
I can't reproduce this. Can anybody? Is the same problem still happening for you? Have you tried using newer versions of Atom?

**Comment by xiaohenry** [comment] 2016-01-13 18:49
I encountered the same issue on new installations of Atom. I'm running Windows 7 and ran into this issue on two machines. One machine was completely new and I only installed Atom, installed sync-settings, and tried running "backup".

**Comment by dirk-thomas** [comment] 2016-01-13 19:05
@xiaohenry Can you please provide similar information as above, especially the Atom and package versions and the exact steps to reproduce the problem.

**Comment by dirk-thomas** [comment] 2016-02-09 18:08
Also in the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Comment by dirk-thomas** [comment] 2016-03-05 07:25
Without further information this can not be debugged. Assuming this is not a problem anymore I will close this ticket. If you are still experiencing the problem please comment with more information.

**Closed by dirk-thomas** 2016-03-05 07:25 UTC
Labels: more information needed

**Comment by TomLingham** [comment] 2016-04-11 08:42
I'm getting the same issue. Behind a corporate network on a machine running Windows 7. Proxy is configured in .apmrc and I have the env variables HTTP_PROXY and HTTPS_PROXY set as well. Not sure if it is related to the proxy however.

**Comment by TomLingham** [comment] 2016-04-14 06:38
Ok, so it appears to be related to SSL snooping on our proxy. Atom has the strict-ssl=false solution in the .apmrc file but there doesn't appear to be a way to set the same for sync-settings as far as I can tell.

**Comment by TomLingham** [comment] 2016-04-15 03:58
Ah ha! So setting NODE_TLS_REJECT_UNAUTHORIZED=0 in my environment variables caused it to work.
