### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/tannerellen/.atom/packages/sync-s...

### ISSUE THREAD

**Issue by tannerellen** [Hackafe/atom-sync-settings#229] opened 2016-03-09 23:59 UTC
[Enter steps to reproduce below:]

Tried to update package and got this error.

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.7.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/tannerellen/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/tannerellen/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/Users/tannerellen/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/Users/tannerellen/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/Users/tannerellen/.atom/packages/sync-settings/lib/sync-settings.coffee:198:18)
    at Object.SyncSettings.checkForUpdate (/Users/tannerellen/.atom/packages/sync-settings/lib/sync-settings.coffee:46:8)
    at Immediate._onImmediate (/Users/tannerellen/.atom/packages/sync-settings/lib/sync-settings.coffee:32:8)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
     -2:38.1.0 find-and-replace:show (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  3x -2:36.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:31.5.0 find-and-replace:show (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  9x -2:30.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:33.3.0 find-and-replace:show (atom-text-editor.editor.mini.is-focused)
  9x -1:30.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:00.0 find-and-replace:show (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:57.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  7x -0:56.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:27.9.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-afterglow-monokai-syntax.theme-one-dark-ui.find-visible)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "afterglow-monokai-syntax"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "d2d8dc78-472d-4eea-b9c5-899800fe3025",
    "_lastBackupHash": "a6ddcc504751a7e1419af118cdbb6279b04994fa",
    "gistId": "4cb7c7830134157cd86d",
    "personalAccessToken": "ee782f33942301d60146f52a0cad68ff03724d1b"
  }
}
```

### Installed Packages

```coffee
# User
afterglow-monokai-syntax, v1.3.3
git-plus, v5.13.0
jshint, v1.8.3
prime-file-icons, v0.2.0
sync-settings, v0.7.0

# Dev
No dev packages
```

**Comment by dirk-thomas** [comment] 2016-03-10 00:10
Duplicate of #194.

In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Closed by dirk-thomas** 2016-03-10 00:10 UTC
