### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/mwalker/.atom/packages/sync-setti...

### ISSUE THREAD

**Issue by tukutela** [Hackafe/atom-sync-settings#199] opened 2016-03-08 01:33 UTC
[Enter steps to reproduce below:]

1. ... Update via Settings
2. ... Hit Update button. 

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.7.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/mwalker/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/mwalker/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/Users/mwalker/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/Users/mwalker/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/Users/mwalker/.atom/packages/sync-settings/lib/sync-settings.coffee:198:18)
    at Object.SyncSettings.checkForUpdate (/Users/mwalker/.atom/packages/sync-settings/lib/sync-settings.coffee:46:8)
    at Immediate._onImmediate (/Users/mwalker/.atom/packages/sync-settings/lib/sync-settings.coffee:32:8)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
     -0:25.7.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "openEmptyEditorOnStart": false,
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "4ac54d76-d05c-4f0c-aed0-7439ebd76690",
    "_lastBackupHash": "1c0c1480d98ab1f5a434892251c8ef144cf160d8",
    "gistId": "8ede8375b830c5f23d8e",
    "personalAccessToken": "06644c5e27932b45dd30b13559f536e2287bc4e5"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-netsuite, v0.4.0
autocomplete-plus, v2.29.1
coffee-compile, v0.21.1
emmet, v2.4.2
sync-settings, v0.7.0

# Dev
No dev packages
```

**Comment by dirk-thomas** [comment] 2016-03-08 01:34
Duplicate of #194.

In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Closed by dirk-thomas** 2016-03-08 01:34 UTC
