### ISSUE TITLE
Feature Request: Blacklist Settings

### ISSUE THREAD

**Issue by deanrather** [Hackafe/atom-sync-settings#126] opened 2015-09-16 03:07 UTC
For example, I have my wakatime API key in my atom-wakatime settings, I don't want this being synced, any more than I want my gist token being synced (which I noticed is being blacklisted from the config.json)

**Comment by jerone** [comment] 2015-09-16 16:48
Ref: https://github.com/Hackafe/atom-sync-settings/pull/97#issuecomment-120666519

**Comment by dirk-thomas** [comment] 2016-02-04 08:01
This is a duplicate of #165 and has been implemented in #177.

**Closed** 2016-02-04 08:01 UTC
Labels: enhancement
