### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/home/jason/.atom/packages/sync-settings...

### ISSUE THREAD

**Issue by jasrusable** [Hackafe/atom-sync-settings#206] opened 2016-03-08 10:40 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Debian GNU/Linux
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.7.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/home/jason/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/home/jason/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/home/jason/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/home/jason/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/home/jason/.atom/packages/sync-settings/lib/sync-settings.coffee:198:18)
    at Object.SyncSettings.checkForUpdate (/home/jason/.atom/packages/sync-settings/lib/sync-settings.coffee:46:8)
    at Immediate._onImmediate (/home/jason/.atom/packages/sync-settings/lib/sync-settings.coffee:32:8)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
     -1:46.3.0 core:close (atom-text-editor.editor.is-focused.vim-mode.normal-mode)
     -1:25 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
     -1:21.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  9x -1:21.3.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  3x -1:19.9.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:50.9.0 core:close (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:47.8.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-solarized-light-syntax.theme-one-light-ui)
```

### Config

```json
{
  "core": {
    "automaticallyUpdate": false,
    "disabledPackages": [
      "swackets"
    ],
    "projectHome": "/home/jason/git",
    "themes": [
      "one-light-ui",
      "solarized-light-syntax"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "f456de03-2fb4-45e5-93aa-910286202239",
    "_lastBackupHash": "4bd4880cb9cd35a9f06ae7fd1e1e26c7c637074c",
    "gistId": "xxxxxxxxx",
    "personalAccessToken": "xxxxxxxxxxxxxxxxxx"
  }
}
```

### Installed Packages

```coffee
# User
atom-paredit, v0.2.0
autocomplete-python, v1.7.0
file-icons, v1.6.18
highlight-line, v0.11.1
highlight-selected, v0.11.2
language-docker, v1.1.6
linter, v1.11.3
linter-clojure, v1.1.2
linter-docker, v0.1.2
linter-flake8, v1.13.0
linter-htmlhint, v1.0.3
linter-js-yaml, v1.2.5
linter-jsonlint, v1.1.6
lisp-paredit, v0.5.2
minimap, v4.20.0
minimap-highlight-selected, v4.4.0
pretty-json, v0.4.1
proto-repl, v1.0.2
python-tools, v0.6.7
react, v0.14.1
sync-settings, v0.7.0
vim-mode, v0.64.0

# Dev
No dev packages
```

**Comment by jerone** [comment] 2016-03-08 10:49
Duplicate of https://github.com/Hackafe/atom-sync-settings/issues/194.

In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Closed by jerone** 2016-03-08 10:49 UTC
