### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/michaelaguiar/.atom/packages/sync...

### ISSUE THREAD

**Issue by michaelaguiar** [Hackafe/atom-sync-settings#214] opened 2016-03-08 17:50 UTC
[Enter steps to reproduce below:]

1. Updated plugin

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.7.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/michaelaguiar/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/michaelaguiar/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/Users/michaelaguiar/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/Users/michaelaguiar/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/Users/michaelaguiar/.atom/packages/sync-settings/lib/sync-settings.coffee:198:18)
    at Object.SyncSettings.checkForUpdate (/Users/michaelaguiar/.atom/packages/sync-settings/lib/sync-settings.coffee:46:8)
    at Immediate._onImmediate (/Users/michaelaguiar/.atom/packages/sync-settings/lib/sync-settings.coffee:32:8)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
     -0:22 project-manager:list-projects (atom-text-editor.editor.is-focused)
  3x -0:20.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:19.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:15 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-galaxy-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide"
    ],
    "themes": [
      "one-dark-ui",
      "galaxy-syntax"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "9b7ef382-9772-4e49-a729-55bd94cfc157",
    "_lastBackupHash": "3639da43f43e8f9b6d66097534f6de0c2ce4fae1",
    "gistId": "79d4322edeb27838aed9",
    "personalAccessToken": "3c06bba17c2d3fa62ff2d77170c19156db785949"
  }
}
```

### Installed Packages

```coffee
# User
galaxy-syntax, v1.1.0
project-manager, v2.7.6
remote-edit, v1.8.24
remote-sync, v3.5.0
sync-settings, v0.7.0

# Dev
No dev packages
```

**Comment by jerone** [comment] 2016-03-08 17:51
Duplicate of https://github.com/Hackafe/atom-sync-settings/issues/194.

In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Closed by jerone** 2016-03-08 17:51 UTC
