### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/scottdensmore/.atom/packages/sync...

### ISSUE THREAD

**Issue by scottdensmore** [Hackafe/atom-sync-settings#213] opened 2016-03-08 16:14 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.7.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/scottdensmore/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/scottdensmore/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/Users/scottdensmore/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/Users/scottdensmore/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/Users/scottdensmore/.atom/packages/sync-settings/lib/sync-settings.coffee:198:18)
    at Object.SyncSettings.checkForUpdate (/Users/scottdensmore/.atom/packages/sync-settings/lib/sync-settings.coffee:46:8)
    at Immediate._onImmediate (/Users/scottdensmore/.atom/packages/sync-settings/lib/sync-settings.coffee:32:8)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
     -3:25.6.0 settings-view:open (atom-text-editor.editor.is-focused)
     -1:58.1.0 core:copy (atom-text-editor#sync-settings.personalAccessToken.editor.mini.is-focused)
```

### Config

```json
{
  "core": {},
  "sync-settings": {
    "_analyticsUserId": "ce6d32a3-206c-4f42-9432-b47ee1460011",
    "_lastBackupHash": "464a7a202805682c4da102784dcec9deadde242c",
    "gistId": "b29b5a7d98e25ce1b6cd",
    "personalAccessToken": "8741e1831fa1ada5479a5e031d778649e11e73fb"
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.5.1
atom-yeoman, v0.3.15
build-xcodebuild, v0.1.0
file-icons, v1.6.18
language-swift, v0.4.0
linter, v1.11.3
linter-swiftlint, v1.1.0
sync-settings, v0.7.0

# Dev
No dev packages
```

**Comment by jerone** [comment] 2016-03-08 16:58
Duplicate of https://github.com/Hackafe/atom-sync-settings/issues/194.

In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Closed by jerone** 2016-03-08 16:58 UTC
