### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/chris/.atom/packages/sync-setting...

### ISSUE THREAD

**Issue by cdornan** [Hackafe/atom-sync-settings#220] opened 2016-03-09 08:09 UTC
I just asked for my packages to be updated.

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.7.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/chris/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/chris/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/Users/chris/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/Users/chris/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/Users/chris/.atom/packages/sync-settings/lib/sync-settings.coffee:198:18)
    at Object.SyncSettings.checkForUpdate (/Users/chris/.atom/packages/sync-settings/lib/sync-settings.coffee:46:8)
    at Immediate._onImmediate (/Users/chris/.atom/packages/sync-settings/lib/sync-settings.coffee:32:8)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
     -9:56.9.0 core:paste (atom-text-editor.editor.mini.is-focused)
 11x -9:56.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -9:30.9.0 core:copy (atom-text-editor.editor.is-focused)
     -9:30.6.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -9:30.3.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -9:29.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -8:50.4.0 core:copy (atom-text-editor.editor.is-focused)
     -8:50.1.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -8:49.9.0 core:paste (atom-text-editor.editor.mini.is-focused)
  4x -8:48.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -8:30.7.0 core:copy (atom-text-editor.editor.is-focused)
     -8:30.4.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -8:30.2.0 core:paste (atom-text-editor.editor.mini.is-focused)
  2x -8:29.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -7:17.3.0 core:save (atom-text-editor.editor.is-focused)
     -1:31.5.0 tabs:split-right (div.title)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "c1ed7b9c-1c0c-4db8-9a79-88e35945a58c",
    "_lastBackupHash": "59b2270b44d6313b9f487a77ca911b58c71c31f8",
    "gistId": "1ca9efcd2e59665ee962",
    "personalAccessToken": "2847cc379f052a10f6039304c4007f5c6d7c47f1"
  }
}
```

### Installed Packages

```coffee
# User
language-haskell, v1.7.2
sync-settings, v0.7.0

# Dev
No dev packages
```

**Comment by jerone** [comment] 2016-03-09 08:15
Duplicate of https://github.com/Hackafe/atom-sync-settings/issues/194.

In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Closed by jerone** 2016-03-09 08:15 UTC
