### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/asunyer/.atom/packages/sync-setti...

### ISSUE THREAD

**Issue by nye** [Hackafe/atom-sync-settings#234] opened 2016-03-11 13:57 UTC
Updating to last version I got this error:

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.2
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.7.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/asunyer/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/asunyer/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/Users/asunyer/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/Users/asunyer/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/Users/asunyer/.atom/packages/sync-settings/lib/sync-settings.coffee:198:18)
    at Object.SyncSettings.checkForUpdate (/Users/asunyer/.atom/packages/sync-settings/lib/sync-settings.coffee:46:8)
    at Immediate._onImmediate (/Users/asunyer/.atom/packages/sync-settings/lib/sync-settings.coffee:32:8)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
  3x -7:22.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -7:14.6.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -7:14.6.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -7:07.3.0 core:move-down (atom-text-editor.editor.is-focused)
     -7:06.4.0 core:save (atom-text-editor.editor.is-focused)
     -6:53.8.0 core:move-up (atom-text-editor.editor.is-focused)
     -6:53.5.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -6:53.1.0 editor:newline (atom-text-editor.editor.is-focused)
  6x -6:48.7.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -6:47.5.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -6:47.4.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -6:41.8.0 core:save (atom-text-editor.editor.is-focused)
     -6:02.7.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-fusion-syntax.theme-nye-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "pigments",
      "terminal-plus",
      "atom-beautify"
    ],
    "ignoredNames": [
      ".DS_Store"
    ],
    "openEmptyEditorOnStart": false,
    "projectHome": "/Applications/MAMP/htdocs",
    "themes": [
      "nye-ui",
      "atom-dark-fusion-syntax"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "e7800ce7-8d1f-4592-bd50-42f004f433b5",
    "_lastBackupHash": "90b8d4542ac587600a1f3ebeccd346e9504db5f7",
    "gistId": "6754a4c1df8191f81f1b",
    "personalAccessToken": "cf81f0e4a321fdefbc2096a5e76f061e1ff65315"
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.5.1
angularjs, v0.3.4
atom-dark-fusion-syntax, v1.1.0
chary-tree-view, v0.2.3
color-picker, v2.1.1
file-type-icons, v0.7.4
highlight-selected, v0.11.2
indent-guide-improved, v1.4.5
language-babel, v2.15.5
language-gitignore, v0.2.0
language-htaccess, v0.1.1
less-than-slash, v0.12.3
linter, v1.11.3
linter-csslint, v1.3.2
linter-eslint, v7.1.1
linter-htmlhint, v1.0.3
linter-jshint, v2.0.2
minimap, v4.20.0
minimap-highlight-selected, v4.4.0
nye-ui, v1.0.2
php-cs-fixer, v2.5.6
project-manager, v2.7.6
react, v0.14.1
sync-settings, v0.7.0

# Dev
No dev packages
```

**Comment by jerone** [comment] 2016-03-11 14:52
Duplicate of #194.

In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Closed by jerone** 2016-03-11 14:52 UTC

**Comment by nye** [comment] 2016-03-11 15:10
Uups, ok, thanks!
