### ISSUE TITLE
Uncaught SyntaxError: Unexpected token w

### ISSUE THREAD

**Issue by MrCitron** [Hackafe/atom-sync-settings#144] opened 2015-11-16 08:31 UTC
Just trying to sync my settings made from a macbook to a ubuntu desktop

1. Installe Atom on ubuntu desktop
2. Setup proxy parameters in /home/xw/.atom/.apm/.apmrc
3. Install sync-settings package and set it up with my gist_id and token
4. Try to restore backup

**Atom Version**: 1.2.0
**System**: Ubuntu 15.10
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.6.0

### Stack Trace

Uncaught SyntaxError: Unexpected token w

```
At file:///usr/share/atom/resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22atom%3A%2F%2Fconfig%22%2C%22initialLine%22%3Anull%2C%22initialColumn%22%3Anull%7D%5D%2C%22windowInitializationScript%22%3A%22%2Fusr%2Fshare%2Fatom%2Fresources%2Fapp.asar%2Fsrc%2Finitialize-application-window.js%22%2C%22resourcePath%22%3A%22%2Fusr%2Fshare%2Fatom%2Fresources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22profileStartup%22%3Afalse%2C%22appVersion%22%3A%221.2.0%22%2C%22shellLoadTime%22%3A707%2C%22initialPaths%22%3A%5B%22atom%3A%2F%2Fconfig%22%5D%7D:1

SyntaxError: Unexpected token w
    at Object.parse (native)
    at /home/xw/.atom/packages/sync-settings/lib/sync-settings.coffee:158:24
    at Object.proto.sendError (/home/xw/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:32:13)
    at /home/xw/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/gists.js:315:29
    at callCallback (/home/xw/.atom/packages/sync-settings/node_modules/github/index.js:743:17)
    at ClientRequest.<anonymous> (/home/xw/.atom/packages/sync-settings/node_modules/github/index.js:809:17)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:259:9)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at onwriteError (_stream_writable.js:304:10)
    at onwrite (_stream_writable.js:322:5)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at fireErrorCallbacks (net.js:442:13)
    at TLSSocket.Socket._destroy (net.js:480:3)
    at WriteWrap.afterWrite (net.js:762:10)
```

### Commands

```
     -0:04.3.0 command-palette:toggle (div.panels-item)
     -0:00.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.9.0 sync-settings:restore (div.panels-item)
```

### Config

```json
{
  "core": {},
  "sync-settings": {
    "_analyticsUserId": "ab7623f0-56ba-47f1-ab0d-a71055dbd464",
    "gistId": "79ce90f0d5d0fb20ce7f",
    "personalAccessToken": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "analytics": false
  }
}
```

### Installed Packages

```coffee
# User
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by dirk-thomas** [comment] 2016-01-13 17:02
I can't reproduce this. Can anybody? Is the same problem still happening for you? Have you tried using newer versions of Atom?

**Comment by MrCitron** [comment] 2016-01-15 12:57
Hi,
I have just upraded to Atom 1.4 and I am still having the problem.
Is this plugin working behind a proxy ?

**Comment by dirk-thomas** [comment] 2016-01-15 18:04
The latest release doesn't support proxies yet. But #167 adds support for it. It would be great if yourcould give it a try and report back.

**Comment by MrCitron** [comment] 2016-01-15 18:45
I have applied the diff from #167 to my local files and then run "update package dependencies: update", but it is not working.

**Comment by dirk-thomas** [comment] 2016-01-15 20:36
Without any further information I can't recommend anything. You might want to try the released version without proxy first to narrow down in which area your problem is.

**Comment by dirk-thomas** [comment] 2016-02-09 18:10
Also in the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Comment by MrCitron** [comment] 2016-02-09 21:12
Thank this token has no important priviledges but I have still revoked it.
Thank you !

**Comment by dirk-thomas** [comment] 2016-03-05 07:28
Without further information this can not be debugged. Assuming this is not a problem anymore I will close this ticket. If you are still experiencing the problem please comment with more information.

**Closed by dirk-thomas** 2016-03-05 07:28 UTC
Labels: more information needed

**Comment by MrCitron** [comment] 2016-03-07 08:28
I still have the same issue with latest atom version and plugin v0.6.0
I will follow issue #141 as it is the exact same issue as this one
