### ISSUE TITLE
Uncaught Error: Cannot find module 'process-nextick-args'

### ISSUE THREAD

**Issue by rwcorbett** [Hackafe/atom-sync-settings#146] opened 2015-11-17 16:25 UTC
[Enter steps to reproduce below:]

1. happens on startup of Atom
2. my Gist is here: https://gist.github.com/rwcorbett/89669613fbcca52e7c95
( this might be due to missing or moving files? )

**Atom Version**: 1.2.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.6.0

### Stack Trace

Uncaught Error: Cannot find module 'process-nextick-args'

```
At module.js:338

Error: Cannot find module 'process-nextick-args'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (C:\Users\rcorbett\AppData\Local\atom\app-1.2.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\rcorbett\.atom\packages\sync-settings\node_modules\analytics-node\node_modules\superagent-proxy\node_modules\proxy-agent\node_modules\pac-proxy-agent\node_modules\get-uri\node_modules\readable-stream\lib\_stream_readable.js:6:23)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (C:\Users\rcorbett\AppData\Local\atom\app-1.2.0\resources\app.asar\src\compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "base16-syntax"
    ],
    "disabledPackages": [
      "language-c",
      "language-clojure",
      "language-go",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-toml",
      "git-control",
      "git-plus",
      "preview",
      "auto-copyright",
      "welcome",
      "soft-wrap-indicator",
      "minimap",
      "jshint"
    ],
    "excludeVcsIgnoredPaths": false,
    "projectHome": "D:\\dev",
    "openEmptyEditorOnStart": false
  },
  "sync-settings": {
    "_analyticsUserId": "9c276f23-d480-41d2-8c2d-cdf7d89c0cc2",
    "gistId": "89669613fbcca52e7c95",
    "personalAccessToken": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "_lastBackupHash": "d5f55d038ff1c5f5f8d799298b9a6352bfa19b3e",
    "syncPackages": false,
    "syncInit": false,
    "syncStyles": false
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.1
atom-beautify, vundefined
atom-material-ui, v0.8.0
base16-syntax, v1.5.0
feedback, v0.38.0
file-icons, v1.6.11
grunt-runner, v0.11.0
highlight-line, v0.11.0
highlight-selected, v0.11.1
minimap-pigments, v0.1.7
pigments, v0.18.1
project-manager, v2.6.5
Sublime-Style-Column-Selection, v1.3.0
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by dirk-thomas** [comment] 2016-02-09 18:12
In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Comment by dirk-thomas** [comment] 2016-02-09 18:12
This is likely a problem with the "older" Atom version. Please upgrade to the current release and comment here if the problem is still happening or has been resolved by that.

**Comment by dirk-thomas** [comment] 2016-03-05 07:28
Without further information this can not be debugged. Assuming this is not a problem anymore I will close this ticket. If you are still experiencing the problem please comment with more information.

**Closed by dirk-thomas** 2016-03-05 07:28 UTC
Labels: more information needed
