### ISSUE TITLE
Uncaught Error: Cannot find module './api/v3.0.0'

### ISSUE THREAD

**Issue by Pszek** [Hackafe/atom-sync-settings#207] opened 2016-03-08 11:16 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.10.5
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.7.0

### Stack Trace

Uncaught Error: Cannot find module './api/v3.0.0'

```
At module.js:338

Error: Cannot find module './api/v3.0.0'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at new module.exports (/Users/maciejc/.atom/packages/sync-settings/node_modules/github/index.js:183:15)
    at Object.SyncSettings.createClient (/Users/maciejc/.atom/packages/sync-settings/lib/sync-settings.coffee:198:18)
    at Object.SyncSettings.backup (/Users/maciejc/.atom/packages/sync-settings/lib/sync-settings.coffee:127:6)
    at atom-workspace.<anonymous> (/Users/maciejc/.atom/packages/sync-settings/lib/sync-settings.coffee:23:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1013:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```

### Commands

```
  2x -1:34.1.0 core:backspace (atom-text-editor.editor.is-focused)
 20x -1:28.5.0 core:move-down (atom-text-editor.editor.is-focused)
  4x -1:24.2.0 core:move-up (atom-text-editor.editor.is-focused)
 11x -1:23.3.0 core:move-down (atom-text-editor.editor.is-focused)
  4x -1:22.3.0 core:move-up (atom-text-editor.editor.is-focused)
 11x -1:21.2.0 core:move-down (atom-text-editor.editor.is-focused)
 22x -1:19.5.0 core:move-up (atom-text-editor.editor.is-focused)
 52x -1:18.3.0 core:move-down (atom-text-editor.editor.is-focused)
 27x -1:12.6.0 core:move-up (atom-text-editor.editor.is-focused)
undefined -1:10.9.0 core:move-down (atom-text-editor.editor.is-focused)
 66x -0:48.8.0 core:move-up (atom-text-editor.editor.is-focused)
 64x -0:45.4.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:41.3.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:39.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:39.3.0 timecop:view (atom-text-editor.editor)
     -0:08.8.0 sync-settings:backup (div.timecop.pane-item.native-key-bindings)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "markdown-preview",
      "linter-xo"
    ],
    "themes": [
      "nucleus-dark-ui",
      "behave-theme"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "3ff1e7f9-f71a-4d22-b880-344b1c46c8a2",
    "_lastBackupHash": "1e00c2436ca3a3094d91a4b49987cc10249138fb",
    "checkForUpdatedBackup": false,
    "gistId": "9a97cf2ec6ec1e6aeccf",
    "personalAccessToken": "716e51850d4f61349ac525971620a6e650b7e545"
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.5.1
atom-alignment, v0.12.1
atom-beautify, v0.28.26
behave-theme, v1.6.0
file-icons, v1.6.18
highlight-line, v0.11.1
highlight-selected, v0.11.2
indent-guide-improved, v1.4.5
language-babel, v2.15.5
linter, v1.11.3
minimap, v4.20.0
minimap-autohide, v0.10.1
minimap-bookmarks, v0.3.0
minimap-cursorline, v0.1.0
minimap-find-and-replace, v4.5.0
minimap-git-diff, v4.2.0
minimap-highlight-selected, v4.4.0
minimap-linter, v1.1.1
minimap-selection, v4.4.0
nucleus-dark-ui, v0.7.10
pigments, v0.24.4
selection-counter, v1.0.0
set-syntax, v0.3.0
svg-preview, v0.7.4
sync-settings, v0.7.0
synced-sidebar, v0.4.3

# Dev
No dev packages
```

**Comment by GijsGoudzwaard** [comment] 2016-03-08 11:56
+1

**Comment by jerone** [comment] 2016-03-08 12:27
Duplicate of https://github.com/Hackafe/atom-sync-settings/issues/194.

In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Closed by jerone** 2016-03-08 12:27 UTC

**Comment by Pszek** [comment] 2016-03-08 13:52
merci beaucoup
