### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/fipo/.atom/packages/sync-settings...

### ISSUE THREAD

**Issue by Fipo** [Hackafe/atom-sync-settings#209] opened 2016-03-08 12:21 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.7.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/fipo/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/fipo/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/Users/fipo/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/Users/fipo/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/Users/fipo/.atom/packages/sync-settings/lib/sync-settings.coffee:198:18)
    at Object.SyncSettings.checkForUpdate (/Users/fipo/.atom/packages/sync-settings/lib/sync-settings.coffee:46:8)
    at Immediate._onImmediate (/Users/fipo/.atom/packages/sync-settings/lib/sync-settings.coffee:32:8)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
     -9:49.1.0 pane:show-item-1 (atom-text-editor.editor.is-focused)
     -9:48.2.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -9:48.2.0 core:cancel (atom-text-editor.editor.is-focused)
     -6:41.3.0 pane:show-item-1 (atom-text-editor.editor.is-focused)
     -6:41.2.0 pane:show-item-2 (atom-text-editor.editor.is-focused)
     -6:39.9.0 pane:show-item-4 (atom-text-editor.editor.is-focused)
     -6:39.1.0 pane:show-item-3 (atom-text-editor.editor.is-focused)
  2x -6:30.5.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
  4x -6:29.3.0 core:move-right (atom-text-editor.editor.is-focused)
     -6:23.4.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:44.1.0 project-find:show (div.panels-item)
     -0:43.8.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:43.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:38.1.0 project-find:show (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
     -0:37.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:36.8.0 project-find:show (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "vim-mode"
    ],
    "packagesWithKeymapsDisabled": [
      "sort-lines"
    ],
    "projectHome": "/Users/fipo/Sites"
  },
  "sync-settings": {
    "_analyticsUserId": "b4f1c1cb-f2ba-405a-9a55-4e849f258446",
    "_lastBackupHash": "f122ba746da094c88a8cfd88d06972013d1a02d0",
    "gistId": "d71d2b5d1e667bf380e9",
    "personalAccessToken": "429f0a3d8f7eb989278b6b116f7bb905b87be944"
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.14.3
atom-jasmine, v0.8.1
highlight-selected, v0.11.2
javascript-snippets, v1.2.1
language-cjsx, v0.3.0
language-javascript-jsx, v0.3.7
language-slim, v0.5.0
linter, v1.11.3
linter-codeclimate, v0.1.2
linter-coffeelint, v1.1.2
linter-csslint, v1.3.2
linter-eslint, v7.0.0
linter-jshint, v2.0.2
linter-jsxhint, v0.1.2
linter-rubocop, v0.4.7
linter-scss-lint, v2.5.1
sync-settings, v0.7.0
tablr, v1.0.2
term3, v0.21.2
trailing-spaces, v0.3.2

# Dev
No dev packages
```

**Comment by jerone** [comment] 2016-03-08 12:27
Duplicate of https://github.com/Hackafe/atom-sync-settings/issues/194.

In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Closed by jerone** 2016-03-08 12:27 UTC
