### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/igorikeda/.atom/packages/sync-set...

### ISSUE THREAD

**Issue by igorikeda** [Hackafe/atom-sync-settings#217] opened 2016-03-08 21:13 UTC

**Comment by jerone** [comment] 2016-03-08 21:17
Duplicate of https://github.com/Hackafe/atom-sync-settings/issues/194.

In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Closed by jerone** 2016-03-08 21:17 UTC
