### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/leeblazek/.atom/packages/sync-set...

### ISSUE THREAD

**Issue by surfjedi** [Hackafe/atom-sync-settings#228] opened 2016-03-09 21:30 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.7.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/leeblazek/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/leeblazek/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/Users/leeblazek/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/Users/leeblazek/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/Users/leeblazek/.atom/packages/sync-settings/lib/sync-settings.coffee:198:18)
    at Object.SyncSettings.checkForUpdate (/Users/leeblazek/.atom/packages/sync-settings/lib/sync-settings.coffee:46:8)
    at Immediate._onImmediate (/Users/leeblazek/.atom/packages/sync-settings/lib/sync-settings.coffee:32:8)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
     -2:00.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  3x -1:53.6.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  4x -1:51.5.0 core:move-up (atom-text-editor.editor.mini.is-focused)
 25x -1:48.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:32.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:32.2.0 git-control:toggle (atom-text-editor.editor)
     -1:04.4.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-jshinter",
      "language-gfm"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "1d23f3c5-7987-4aa9-a1c2-7231bbc24c7b",
    "_lastBackupHash": "4daaeca5e97f5993b13195cecaf10449e9c3d1cf",
    "gistId": "7243db77d0557b19b081",
    "personalAccessToken": "c6f364f4834c8b9472d275432e78b4dfbc334094"
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.4
atom-jade, v0.3.0
autoclose-html, v0.23.0
editor-settings, v1.0.4
editorconfig, v1.2.4
emmet, v2.4.2
git-control, v0.4.0
git-plus, v5.13.0
language-markdown, v0.11.0
linter, v1.11.3
linter-csslint, v1.3.2
linter-htmlhint, v1.0.3
linter-jade, v0.3.2
linter-jshint, v2.0.2
markdown-preview-plus, v2.2.2
minimap, v4.20.0
pigments, v0.24.5
project-manager, v2.7.6
source-preview-babel, v0.1.1
source-preview-jade, v0.1.1
source-preview-react, v0.2.0
sync-settings, v0.7.0
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by dirk-thomas** [comment] 2016-03-09 21:37
Duplicate of #194.

In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Closed by dirk-thomas** 2016-03-09 21:37 UTC
