### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/home/daniel/.atom/packages/sync-setting...

### ISSUE THREAD

**Issue by danielvoicu** [Hackafe/atom-sync-settings#205] opened 2016-03-08 09:53 UTC
1. I was editing a .less file.
2. Got a notification about an update, ran the update of the plugin.
3. This error was thrown.

**Atom Version**: 1.5.4
**System**: Ubuntu 14.04.4
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.7.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/home/daniel/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/home/daniel/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/home/daniel/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/home/daniel/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/home/daniel/.atom/packages/sync-settings/lib/sync-settings.coffee:198:18)
    at Object.SyncSettings.checkForUpdate (/home/daniel/.atom/packages/sync-settings/lib/sync-settings.coffee:46:8)
    at Immediate._onImmediate (/home/daniel/.atom/packages/sync-settings/lib/sync-settings.coffee:32:8)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
     -0:37.4.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-monokai-seti.theme-seti-ui)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "preview",
      "preview-plus",
      "tool-bar",
      "meteor-api",
      "pigments",
      "linter-tidy"
    ],
    "themes": [
      "seti-ui",
      "monokai-seti"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "964485fd-706a-4a06-8d94-90eb632ace09",
    "_lastBackupHash": "ca5235c1007a3af09691294a5d0295566bda7255",
    "gistId": "da1d43d51fb25f7a076d",
    "personalAccessToken": "70cfa4e2d0b8cf4d66e55f9b3c1433e767ec0c1c"
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.4
atom-beautify, v0.28.26
atom-html-preview, v0.1.16
atom-ternjs, v0.13.2
color-picker, v2.1.1
csslint, v1.1.4
language-babel, v2.15.5
linter, v1.11.3
linter-csslint, v1.3.2
linter-jshint, v2.0.2
minimap, v4.20.0
monokai-seti, v0.7.0
open-recent, v5.0.0
package-sync, v1.0.0
react, v0.14.1
seti-ui, v0.9.1
sync-settings, v0.7.0
term3, v0.21.2

# Dev
No dev packages
```

**Comment by jerone** [comment] 2016-03-08 10:49
Duplicate of https://github.com/Hackafe/atom-sync-settings/issues/194.

In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Closed by jerone** 2016-03-08 10:49 UTC

**Comment by danielvoicu** [comment] 2016-03-08 10:53
Thanks for letting me know, I didn't notice that. I've removed that part from my original issue report, and I'll also revoke the token.
