### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/donjones/.atom/packages/sync-sett...

### ISSUE THREAD

**Issue by newelement** [Hackafe/atom-sync-settings#212] opened 2016-03-08 15:11 UTC
[Enter steps to reproduce below:]

1.tried to update package

**Atom Version**: 1.6.0-beta7
**System**: Mac OS X 10.11.3
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.7.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/donjones/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/donjones/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/Users/donjones/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/Users/donjones/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/Users/donjones/.atom/packages/sync-settings/lib/sync-settings.coffee:198:18)
    at Object.SyncSettings.checkForUpdate (/Users/donjones/.atom/packages/sync-settings/lib/sync-settings.coffee:46:8)
    at Immediate._onImmediate (/Users/donjones/.atom/packages/sync-settings/lib/sync-settings.coffee:32:8)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
  9x -1:51.8.0 core:move-left (atom-text-editor.editor.is-focused)
 21x -1:50.3.0 core:backspace (atom-text-editor.editor.is-focused)
 15x -1:44.7.0 core:move-left (atom-text-editor.editor.is-focused.autocomplete-active)
  7x -1:43.1.0 core:move-right (atom-text-editor.editor.is-focused)
  8x -1:42.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:40.6.0 core:move-right (atom-text-editor.editor.is-focused)
 21x -1:40.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:33.5.0 core:copy (atom-text-editor.editor.is-focused)
     -1:31.5.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -1:31.5.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -1:31.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:31.2.0 core:paste (atom-text-editor.editor.is-focused)
 10x -1:30.8.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:29 core:move-right (atom-text-editor.editor.is-focused)
  7x -1:28.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:25.6.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "welcome"
    ],
    "themes": [
      "one-dark-ui",
      "an-old-hope-syntax"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "61be0196-3c11-42c0-ace7-315ecdf8de1c",
    "_lastBackupHash": "5575c1ddf17e01996b4a717cdea00bdb05404640",
    "gistId": "a10510ae48a3a8050427",
    "personalAccessToken": "2f862505eb58950fc5713c6b92f0f432cfa6502d"
  }
}
```

### Installed Packages

```coffee
# User
Remote-FTP, v0.7.20
an-old-hope-syntax, v0.5.0
angularjs, v0.3.4
atom-beautify, v0.28.26
atom-json-editor, v0.4.1
atom-wordpress, v0.3.0
autocomplete-html-entities, v0.1.0
autocomplete-php, v0.3.7
chary-tree-view, v0.2.3
color-picker, v2.1.1
docblockr, v0.7.3
emmet, v2.4.2
file-icons, v1.6.18
flex-tool-bar, v0.8.1
git-control, v0.4.0
less-than-slash, v0.12.3
linter, v1.11.3
linter-csslint, v1.3.2
linter-htmlhint, v1.0.3
linter-jshint, v2.0.2
linter-jsonlint, v1.1.6
linter-php, v1.2.0
linter-scss-lint, v2.5.1
minimap, v4.20.0
pigments, v0.24.4
project-viewer, v0.2.31
sync-settings, v0.7.0
terminal-plus, v0.14.5
tool-bar, v0.3.0

# Dev
No dev packages
```

**Comment by jerone** [comment] 2016-03-08 15:37
Duplicate of https://github.com/Hackafe/atom-sync-settings/issues/194.

In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Closed by jerone** 2016-03-08 15:37 UTC
