### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/home/ivlis/.atom/packages/sync-settings...

### ISSUE THREAD

**Issue by ivlis** [Hackafe/atom-sync-settings#195] opened 2016-03-07 22:14 UTC
I've got this error immediatly after updating to 0.7.0

**Atom Version**: 1.5.4
**System**: linux 4.4.1-2-ARCH
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.7.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/home/ivlis/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/home/ivlis/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/home/ivlis/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/home/ivlis/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/home/ivlis/.atom/packages/sync-settings/lib/sync-settings.coffee:198:18)
    at Object.SyncSettings.checkForUpdate (/home/ivlis/.atom/packages/sync-settings/lib/sync-settings.coffee:46:8)
    at Immediate._onImmediate (/home/ivlis/.atom/packages/sync-settings/lib/sync-settings.coffee:32:8)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
     -8:37.3.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -8:35.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -8:11.7.0 blur (atom-text-editor.editor.mini.is-focused)
     -8:07.3.0 autocomplete-python:go-to-definition (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
 16x -8:07.3.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  2x -3:33.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:31.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 40x -3:21 blur (atom-text-editor.editor.mini.is-focused)
     -2:17.8.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
 33x -2:17.7.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-flake8",
      "linter-chktex",
      "atom-beautify"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "XXXXXXXX",
    "_lastBackupHash": "XXXXXXX",
    "gistId": "XXXXXXX",
    "personalAccessToken": "XXXXXXX"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-python, v1.7.0
file-icons, v1.6.18
hyperclick, v0.0.35
language-latex, v0.6.1
latextools, v0.8.0
linter, v1.11.3
linter-coffeelint, v1.1.2
open-recent, v5.0.0
sync-settings, v0.7.0
vim-mode-plus, v0.23.0

# Dev
No dev packages
```

**Comment by dirk-thomas** [comment] 2016-03-07 22:42
Duplicate of #194.

**Closed by dirk-thomas** 2016-03-07 22:42 UTC
Labels: duplicate
