### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/<User>/.atom/packages/sync-setting...

### ISSUE THREAD

**Issue by cento** [Hackafe/atom-sync-settings#225] opened 2016-03-09 11:35 UTC
1. update using the Atom interface
2. Nothing else!

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.7.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/<User>/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/<User>/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/Users/<User>/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/Users/<User>/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/Users/<User>/.atom/packages/sync-settings/lib/sync-settings.coffee:205:9)
    at Object.SyncSettings.checkForUpdate (/Users/<User>/.atom/packages/sync-settings/lib/sync-settings.coffee:18:3)
    at Immediate._onImmediate (/Users/<User>/.atom/packages/sync-settings/lib/sync-settings.coffee:35:9)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
     -0:25.9.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-solarized-dark-syntax.theme-atom-dark-ui.find-visible)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "customFileTypes": {
      "source.cpp": [
        "h"
      ]
    },
    "disabledPackages": [
      "autocomplete-html",
      "language-clojure",
      "language-csharp",
      "language-go",
      "language-html",
      "language-java",
      "language-javascript",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-sass",
      "language-sql",
      "language-xml",
      "language-yaml",
      "metrics",
      "open-on-github",
      "gutter-shadow",
      "linter",
      "linter-gcc",
      "autocomplete-ctags"
    ],
    "openEmptyEditorOnStart": false,
    "projectHome": "/Users/<User>/Desktop/Devel",
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "eab26d2d-2383-4974-b13e-8b3441767b15",
    "_lastBackupHash": "0824307cbbf706238a157355441ace9e36cb24a8",
    "analytics": false,
    "gistId": "23185ccac2e73be6df03",
    "personalAccessToken": "50fd914ba3c6dc4fb6e63237cead87dec460136d"
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.5.1
atom-sync, v0.6.0
autocomplete-clang, v0.8.9
block-travel, v1.0.4
build, v0.55.0
clang-format, v1.25.0
clipboard-history, v0.6.6
file-icons, v1.6.18
file-watcher, v0.4.0
git-difftool, v0.2.7
highlight-line, v0.11.1
language-rust, v0.4.6
minimap, v4.20.0
minimap-autohide, v0.10.1
racer, v0.18.0
remote-atom, v1.3.9
rust-api-docs-helper, v0.5.1
symbol-gen, v1.0.0
sync-settings, v0.7.0
terminal-plus, v0.14.5
time-status, v1.1.2
toggle-gutter, v0.2.2

# Dev
No dev packages
```

**Comment by jerone** [comment] 2016-03-09 11:37
Duplicate of https://github.com/Hackafe/atom-sync-settings/issues/194.

In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Closed by jerone** 2016-03-09 11:37 UTC
