### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/USER_NAME/.atom/packages/sync-settin...

### ISSUE THREAD

**Issue by dorakueyon** [Hackafe/atom-sync-settings#233] opened 2016-03-11 04:47 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.2
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.7.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/yoheia/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/yoheia/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/Users/yoheia/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/Users/yoheia/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/Users/yoheia/.atom/packages/sync-settings/lib/sync-settings.coffee:198:18)
    at Object.SyncSettings.checkForUpdate (/Users/yoheia/.atom/packages/sync-settings/lib/sync-settings.coffee:46:8)
    at Immediate._onImmediate (/Users/yoheia/.atom/packages/sync-settings/lib/sync-settings.coffee:32:8)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
     -5:26.5.0 core:move-down (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -5:26 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode.autocomplete-active)
     -5:18.3.0 core:copy (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -5:15.6.0 core:move-up (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -5:15.4.0 editor:newline (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -5:15.1.0 core:paste (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  2x -5:14.6.0 core:move-down (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  2x -5:13.9.0 core:move-up (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
 10x -5:12.3.0 core:move-left (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -5:09.6.0 core:move-down (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  7x -5:09.0 core:move-right (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -5:07.4.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode.autocomplete-active)
     -4:43.9.0 editor:newline (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
 17x -4:41.7.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -2:31.8.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:33.7.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "regex-railroad-diagram"
    ],
    "packagesWithKeymapsDisabled": [
      "term"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "60927dd9-7bc2-49b8-a78f-a08d8f658ad3",
    "_lastBackupHash": "c6c3913c3a7d303ef80eb9aeae9fbe8807db5651",
    "gistId": "5a8d7a2a09f5eb6c2e2d",
    "personalAccessToken": "38ffbd1d22a942028d305bd7dc3cb57181453510"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-paths, v1.0.2
color-picker, v2.1.1
cursor-history, v0.5.9
file-icons, v1.6.18
highlight-column, v0.5.1
highlight-line, v0.11.1
highlight-selected, v0.11.2
image-copipe, v0.3.1
linter, v1.11.3
markdown-preview-plus, v2.2.2
minimap, v4.20.0
minimap-autohide, v0.10.1
minimap-git-diff, v4.2.0
minimap-highlight-selected, v4.4.0
minimap-pigments, v0.2.0
project-manager, v2.7.6
sync-settings, v0.7.0
term3, v0.21.2
vim-mode, v0.65.0
vim-mode-visual-block, v0.2.15

# Dev
No dev packages
```

**Comment by dirk-thomas** [comment] 2016-03-11 06:33
Duplicate of #194.

In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Closed by dirk-thomas** 2016-03-11 06:33 UTC
