### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/xxx/.atom/packages/sync-set...

### ISSUE THREAD

**Issue by gurrinder** [Hackafe/atom-sync-settings#200] opened 2016-03-08 02:33 UTC
[Enter steps to reproduce below:]

1. update atom package
**Atom Version**: 1.5.4
**System**: Mac OS X 10.10.4
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.7.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/xxx/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/xxx/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/Users/xxx/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/Users/xxx/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/Users/xxxx/.atom/packages/sync-settings/lib/sync-settings.coffee:300:16)
    at Object.SyncSettings.checkForUpdate (/Users/xxxx/.atom/packages/sync-settings/lib/sync-settings.coffee:61:21)
    at Immediate._onImmediate (/Users/xxx/.atom/packages/sync-settings/lib/sync-settings.coffee:44:19)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
     -0:50 core:close (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:49.9.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-seti-syntax.theme-seti-ui)
     -0:49.7.0 core:close (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:49.7.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-seti-syntax.theme-seti-ui)
     -0:49.3.0 core:close (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:49.2.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-seti-syntax.theme-seti-ui)
     -0:47.2.0 core:close (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:47.2.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-seti-syntax.theme-seti-ui)
     -0:46.6.0 settings-view:open (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:46.6.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-seti-syntax.theme-seti-ui)
     -0:21 incompatible-packages:view (div.incompatible-packages-status.inline-block.text.text-error)
  2x -0:20.9.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-seti-syntax.theme-seti-ui)
     -0:13.9.0 incompatible-packages:view (div.incompatible-packages-status.inline-block.text.text-error)
     -0:13.9.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-seti-syntax.theme-seti-ui)
     -0:12.9.0 incompatible-packages:view (div.incompatible-packages-status.inline-block.text.text-error)
     -0:09.4.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-seti-syntax.theme-seti-ui)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "symbols-view",
      "language-slim",
      "ruby-slim",
      "save-session",
      "auto-reveal-in-sidebar"
    ],
    "openEmptyEditorOnStart": false,
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "4b8aeacf-7453-4688-97c8-27520265441c",
    "_lastBackupHash": "be111f37dc197b630e1dadb75618598db044dd80",
    "gistId": "81b521099c67511e36b7",
    "personalAccessToken": "4b2e28963130d49b04a0710b86ca0e13aeda7cc4"
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.5.1
angularjs, v0.3.4
atom-ctags, v4.5.0
atom-jade, v0.3.0
atom-pair, v2.0.10
autocomplete-paths, v1.0.2
circle-ci, v0.10.1
ctrl-last-tab, v0.3.0
grunt-runner, v0.14.0
language-haml, v0.23.15
linter, v1.11.3
linter-coffeelint, v1.1.2
linter-csslint, v1.3.2
linter-erb, v1.0.2
linter-js-yaml, v1.2.5
linter-jshint, v2.0.2
linter-jsonlint, v1.1.6
linter-ruby, v1.2.2
linter-scss-lint, v2.5.1
linter-slim, v1.0.0
mocha, v0.0.7
mocha-test-runner, v0.4.7
node-debugger, v1.4.4
project-manager, v2.7.6
seti-syntax, v0.4.1
seti-ui, v0.9.1
slim-language, v2.2.0
sync-settings, v0.7.0
synced-sidebar, v0.4.3
trailing-spaces, v0.3.2

# Dev
No dev packages
```

**Comment by dirk-thomas** [comment] 2016-03-08 05:11
Duplicate of #194.

In the above error report you have shared your personalAccessToken. You must revoke it to prevent abuse.

**Comment by gurrinder** [comment] 2016-03-08 05:12
Oh thanks!

**Closed** 2016-03-08 05:11 UTC
Labels: duplicate
