### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/djbelieny/.atom/packages/sync-set...

### ISSUE THREAD

**Issue by djbelieny** [Hackafe/atom-sync-settings#219] opened 2016-03-08 23:13 UTC
Trying to update plugins when this error popped up. 

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.7.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/djbelieny/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/djbelieny/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/Users/djbelieny/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/Users/djbelieny/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/Users/djbelieny/.atom/packages/sync-settings/lib/sync-settings.coffee:198:18)
    at Object.SyncSettings.checkForUpdate (/Users/djbelieny/.atom/packages/sync-settings/lib/sync-settings.coffee:46:8)
    at Immediate._onImmediate (/Users/djbelieny/.atom/packages/sync-settings/lib/sync-settings.coffee:32:8)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
     -7:36.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -7:32.3.0 command-palette:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  6x -7:28.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -7:24 core:confirm (atom-text-editor.editor.mini.is-focused)
     -7:24 settings-view:open (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -7:12.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -7:08.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -6:59.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 10x -6:48.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -6:34.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:29.2.0 command-palette:toggle (atom-text-editor.editor.is-focused)
 14x -3:24.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -3:12.1.0 core:move-up (atom-text-editor.editor.mini.is-focused)
  3x -3:09.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
 18x -3:08.7.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -2:57.9.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-base16-tomorrow-dark-theme.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "projectHome": "/Users/djbelieny/projects/repos",
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "95fdd89d-60cf-4732-be78-cd7d9f8dcad6",
    "_lastBackupHash": "96c58d1eaca38ffc7ddbce7457387e8f806b638f",
    "gistId": "5ea7b34fd3f4f3ee8d67",
    "personalAccessToken": "017dc853b4406da9daca210f7da43a0fff8df3b3"
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.1
atom-html-preview, v0.1.16
autocomplete-modules, v1.4.1
browser-plus, v0.0.54
change-case, v0.6.0
color-picker, v2.1.1
docblockr, v0.7.3
drunken-php, v0.2.1
express-complete, v0.2.0
file-icons, v1.6.18
language-api-blueprint, v1.0.2
language-log, v1.4.0
language-lua, v0.9.4
linter, v1.11.3
linter-jsonlint, v1.1.6
linter-php, v1.2.0
minimap, v4.20.0
nodejs-snippets, v2.0.0
php-twig, v4.0.0
pigments, v0.24.4
project-plus, v0.7.1
sync-settings, v0.7.0
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by jerone** [comment] 2016-03-08 23:16
Duplicate of https://github.com/Hackafe/atom-sync-settings/issues/194.

In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Closed by jerone** 2016-03-08 23:16 UTC
