### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/xavier/.atom/packages/sync-settin...

### ISSUE THREAD

**Issue by RedSentry** [Hackafe/atom-sync-settings#201] opened 2016-03-08 07:59 UTC
[Enter steps to reproduce below:]

1. Tried to update
2. Then this happened

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.1
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.7.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/xavier/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/xavier/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/Users/xavier/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/Users/xavier/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/Users/xavier/.atom/packages/sync-settings/lib/sync-settings.coffee:198:18)
    at Object.SyncSettings.checkForUpdate (/Users/xavier/.atom/packages/sync-settings/lib/sync-settings.coffee:46:8)
    at Immediate._onImmediate (/Users/xavier/.atom/packages/sync-settings/lib/sync-settings.coffee:32:8)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
     -0:40.3.0 sync-settings:restore (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-seti-ui)
     -0:35 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-seti-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "emmet"
    ],
    "themes": [
      "seti-ui",
      "one-dark-syntax"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "50838dac-3f07-4c01-a668-0f823d1a021f",
    "_lastBackupHash": "2f9d6288f51d0344142bd378791c7a7c9f89c033",
    "gistId": "8973cb5843b9ac44edbf",
    "personalAccessToken": "6eab625e9ded14a5f60576c60ce35840b3af2b0c"
  }
}
```

### Installed Packages

```coffee
# User
browser-refresh-on-save, v0.0.4
linter, v1.11.3
linter-csslint, v1.3.2
linter-htmlhint, v1.0.3
linter-jshint, v2.0.2
livereload, v0.4.4
pigments, v0.24.4
seti-icons, v0.4.5
seti-ui, v0.9.1
sync-settings, v0.7.0
tag, v0.3.0
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by dirk-thomas** [comment] 2016-03-08 08:00
Duplicate of #194.

In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Closed by dirk-thomas** 2016-03-08 08:00 UTC
