### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/jwomack/.atom/packages/sync-setti...

### ISSUE THREAD

**Issue by jameswomack** [Hackafe/atom-sync-settings#198] opened 2016-03-08 01:10 UTC
[Enter steps to reproduce below:]

1. Try to update the package

**Atom Version**: 1.6.0-beta4
**System**: Mac OS X 10.11.3
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.7.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/jwomack/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/jwomack/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/Users/jwomack/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/Users/jwomack/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/Users/jwomack/.atom/packages/sync-settings/lib/sync-settings.coffee:198:18)
    at Object.SyncSettings.checkForUpdate (/Users/jwomack/.atom/packages/sync-settings/lib/sync-settings.coffee:46:8)
    at Immediate._onImmediate (/Users/jwomack/.atom/packages/sync-settings/lib/sync-settings.coffee:32:8)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "autoclose-html",
      "tree-view"
    ],
    "themes": [
      "seti-ui",
      "solarized-dark-syntax"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "d971b179-c80d-43cb-b338-465335d05445",
    "_lastBackupHash": "c9a94f12a0747785e171240293531d41af635fc1",
    "gistId": "25dc21963f54beda5abe",
    "personalAccessToken": "13cc28741a0492dee19103fcee6cc1d856bec40a"
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v3.0.0
atom-alignment, v0.12.1
atom-grails, v0.1.0
atom-html-preview, v0.1.16
atom-import-sort, v0.6.0
atom-jade, v0.3.0
atom-pair, v2.0.10
atom-ternjs, v0.13.2
atom-wallaby, v1.0.7
autocomplete-paths, v1.0.2
color-picker, v2.1.1
csslint, v1.1.4
highlight-column, v0.5.1
highlight-line, v0.11.1
highlight-selected, v0.11.2
ide-flow, v0.8.0
js-refactor, v0.6.0
language-babel, v2.15.5
language-gitignore, v0.2.0
language-javascript-jsx, v0.3.7
linter, v1.11.3
linter-eslint, v7.0.0
linter-jscs, v3.4.8
minimap, v4.20.0
nuclide, v0.120.0
pigments, v0.24.4
project-manager, v2.7.6
react, v0.14.1
refactor, v0.6.0
seti-ui, v0.9.1
sync-settings, v0.7.0
travis-ci-status, v1.0.0
webbox-color, v0.5.9

# Dev
No dev packages
```

**Comment by dirk-thomas** [comment] 2016-03-08 01:20
Duplicate of #194

**Comment by dirk-thomas** [comment] 2016-03-08 01:21
In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Closed by dirk-thomas** 2016-03-08 01:20 UTC
Labels: duplicate
