### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/[...]/.atom/packages/sync-sett...

### ISSUE THREAD

**Issue by atalargo** [Hackafe/atom-sync-settings#222] opened 2016-03-09 09:50 UTC
[Enter steps to reproduce below:]

1. Launch update of atom-sync-settings to version 0.7.0
2. Wait update finished...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.10.5
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.7.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '[...]/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '[...]/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/[...]/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/[...]/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/[...]/.atom/packages/sync-settings/lib/sync-settings.coffee:300:16)
    at Object.SyncSettings.checkForUpdate (/[...]/.atom/packages/sync-settings/lib/sync-settings.coffee:61:21)
    at Immediate._onImmediate (/[...]/.atom/packages/sync-settings/lib/sync-settings.coffee:44:19)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
 14x -6:45.7.0 core:close (atom-text-editor.editor.is-focused)
     -4:45.8.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -4:41.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:32.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:30.4.0 core:save (atom-text-editor.editor.is-focused)
     -4:30.4.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -4:30.4.0 core:cancel (atom-text-editor.editor.is-focused)
     -4:26.5.0 core:close (atom-text-editor.editor.is-focused)
     -4:24.8.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -4:16.2.0 core:close (atom-text-editor.editor.is-focused)
  2x -0:45.5.0 symbols-view:go-to-declaration (atom-text-editor.editor.is-focused)
  2x -0:19.4.0 core:close (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "behat-atom",
      "ruby-block-converter",
      "tree-view-open-files",
      "w3c-validation",
      "compare-files",
      "my-utils",
      "rsense",
      "coffee-lint",
      "linter-coffeescript",
      "ruby-string-interpolation2",
      "ruby-string-interpolation",
      "copy-as-rtf"
    ],
    "excludeVcsIgnoredPaths": false,
    "followSymlinks": true
  },
  "sync-settings": {
    "_analyticsUserId": "691400ac-e07c-40f8-a343-915f0c9ac6fa",
    "_lastBackupHash": "7bafcba4fc594a9a03b6f2bf81fb262cb8c9eda1",
    "gistId": "[...]",
    "personalAccessToken": "[...]"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.26
autoclose-html, v0.23.0
git-log, v0.4.1
git-tab-status, v1.9.2
jshint, v1.8.3
jsonlint, v1.1.2
language-diff, v0.4.0
language-slim, v0.5.0
language-twig, v1.6.2
less-than-slash, v0.12.3
linter, v1.11.3
linter-coffeelint, v1.1.2
linter-csslint, v1.3.2
linter-flow, v4.1.0
linter-haml, v1.1.0
linter-js-yaml, v1.2.5
linter-php, v1.2.0
linter-phpcs, v1.3.1
linter-rubocop, v0.4.7
linter-ruby, v1.2.2
linter-scss-lint, v2.5.1
linter-slim, v1.0.0
markdown-format, v2.5.1
php-twig, v4.0.0
phpunit, v1.2.0
phpunit-snippets, v0.1.0
preview-plus, v1.2.6
project-manager, v2.7.6
save-session, v0.16.0
symbols-tree-view, v0.11.0
symfony-snippets, v0.3.0
sync-settings, v0.7.0
text-manipulation, v0.6.0

# Dev
No dev packages
```

**Comment by atalargo** [comment] 2016-03-09 09:53
Apperently it duplicate issue #194

**Comment by jerone** [comment] 2016-03-09 09:56
Duplicate of https://github.com/Hackafe/atom-sync-settings/issues/194.

In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Closed by jerone** 2016-03-09 09:56 UTC
