### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/casper/.atom/packages/sync-settin...

### ISSUE THREAD

**Issue by caspersg** [Hackafe/atom-sync-settings#218] opened 2016-03-08 22:43 UTC
[Enter steps to reproduce below:]

1. update sync-settings package to 0.7.0

**Atom Version**: 1.5.4
**System**: Mac OS X 10.10.5
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.7.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/casper/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/casper/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/Users/casper/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/Users/casper/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/Users/casper/.atom/packages/sync-settings/lib/sync-settings.coffee:205:9)
    at Object.SyncSettings.checkForUpdate (/Users/casper/.atom/packages/sync-settings/lib/sync-settings.coffee:18:3)
    at Immediate._onImmediate (/Users/casper/.atom/packages/sync-settings/lib/sync-settings.coffee:35:9)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
     -2:28.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -2:28 blur (atom-text-editor.editor.mini.is-focused)
     -2:20 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -2:14.9.0 blur (atom-text-editor.editor.mini.is-focused)
     -1:52.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  9x -1:50.7.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:49.9.0 vim-mode-plus:activate-insert-mode (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:49.5.0 editor:newline (atom-text-editor.editor.vim-mode-plus.is-focused.insert-mode)
  5x -0:48.9.0 core:backspace (atom-text-editor.editor.vim-mode-plus.is-focused.insert-mode)
     -0:46.8.0 core:save (atom-text-editor.editor.vim-mode-plus.is-focused.insert-mode)
  9x -0:45.1.0 blur (atom-text-editor.editor.vim-mode-plus.is-focused.insert-mode)
     -0:39.7.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-base16-tomorrow-dark-theme.theme-one-dark-ui.seti-ui-no-icons)
  9x -0:39.7.0 blur (atom-text-editor.editor.is-focused.vim-mode-plus.insert-mode)
     -0:23.2.0 pane:split-left (a.icon.icon-plus)
 15x -0:23.2.0 blur (div.panels-item)
     -0:11.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "vim-mode",
      "vim-surround",
      "vim-mode-clipboard-plus",
      "vim-mode-plus-move-to-symbols",
      "vim-mode-visual-block",
      "clip-history",
      "atom-keyboard-macros-vim",
      "ex-mode"
    ],
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "96163a79-3988-48cf-b372-6060c992b2ab",
    "_lastBackupHash": "9775d24b6b89f26f5f6c686b72c805f3a786303b",
    "gistId": "6f768f6123518dc82a26",
    "personalAccessToken": "465975488181291436da36119a2e992731ce259a"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.26
auto-detect-indentation, v1.0.0
clipboard-plus, v0.5.1
color-picker, v2.1.1
ctrl-last-tab, v0.3.0
cursor-history, v0.5.9
file-icons, v1.6.18
highlight-selected, v0.11.2
last-cursor-position, v0.9.0
linter, v1.11.3
linter-eslint, v7.0.0
linter-jslint, v10.2.0
linter-sass-lint, v1.1.2
minimap, v4.20.0
project-manager, v2.7.6
symbol-gen, v1.0.0
sync-settings, v0.7.0
toggle-packages, v1.1.0
vim-mode-plus, v0.23.0
vim-mode-plus-move-selected-text, v0.4.1
vim-mode-plus-subword-movement, v0.2.2

# Dev
No dev packages
```

**Comment by jerone** [comment] 2016-03-08 22:53
Duplicate of https://github.com/Hackafe/atom-sync-settings/issues/194.

In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Closed by jerone** 2016-03-08 22:53 UTC
