### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/nieke/.atom/packages/sync-setting...

### ISSUE THREAD

**Issue by Niekes** [Hackafe/atom-sync-settings#230] opened 2016-03-10 16:06 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.7.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/nieke/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/nieke/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/Users/nieke/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/Users/nieke/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/Users/nieke/.atom/packages/sync-settings/lib/sync-settings.coffee:198:18)
    at Object.SyncSettings.checkForUpdate (/Users/nieke/.atom/packages/sync-settings/lib/sync-settings.coffee:46:8)
    at Immediate._onImmediate (/Users/nieke/.atom/packages/sync-settings/lib/sync-settings.coffee:32:8)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
     -1:02.9.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-monokai.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "atom-htmltidy",
      "linter-php"
    ],
    "openEmptyEditorOnStart": false,
    "projectHome": "/Users/nieke/Sites",
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "999",
    "_lastBackupHash": "6de45e45fb90b902253426d011abadf5552edaa2",
    "gistId": "f348994bb4e76afbcd14",
    "personalAccessToken": "57d9b2d033c32c03217d9ff827448a472930c793"
  }
}
```

### Installed Packages

```coffee
# User
atom-jade, v0.3.0
atom-ternjs, v0.13.2
browser-refresh, v0.9.0
color-picker, v2.1.1
emmet, v2.4.2
file-icons, v1.6.18
highlight-selected, v0.11.2
jshint, v1.8.3
linter, v1.11.3
linter-jsonlint, v1.1.6
minimap, v4.20.0
monokai, v0.18.0
pigments, v0.24.5
rest-client, v0.5.1
sync-settings, v0.7.0

# Dev
No dev packages
```

**Comment by dirk-thomas** [comment] 2016-03-10 17:14
Duplicate of #194.

In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Closed by dirk-thomas** 2016-03-10 17:14 UTC
