### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/xxxxx/.atom/packages/sync-setti...

### ISSUE THREAD

**Issue by RVN-BR** [Hackafe/atom-sync-settings#231] opened 2016-03-10 17:20 UTC
[Enter steps to reproduce below:]

1. I was stopped on the package settings tab of another package when the notice came up;
2. Either it was caused by an upgrade to 0.7.0 or it was just in the initialization process...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.10.5
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.7.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/xxxxx/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/xxxxx/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
  at Error (native)
  at Object.fs.openSync (fs.js:549:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
  at Object.fs.readFileSync (fs.js:397:15)
  at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
  at Object.module.exports (/Users/xxxxxx/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
  at new module.exports (/Users/xxxxx/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
  at Object.SyncSettings.createClient (/Users/xxxxxx/.atom/packages/sync-settings/lib/sync-settings.coffee:205:9)
  at Object.SyncSettings.checkForUpdate (/Users/xxxxx/.atom/packages/sync-settings/lib/sync-settings.coffee:18:3)
  at Immediate._onImmediate (/Users/xxxxx/.atom/packages/sync-settings/lib/sync-settings.coffee:44:19)
  at processImmediate [as _immediateCallback] (timers.js:374:17)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "project-manager",
      "tree-view",
      "linter"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "a4c0e775-dfcb-4e8e-8da2-a84933d83585",
    "_lastBackupHash": "1b840498fc5bb52c51df0e07d629ba3f4df9fad4",
    "gistId": "b9f28fe1aff9b0bbe67b",
    "personalAccessToken": "450e79dc22ee6b75aeaa48d20e2bc730fcf9400d",
    "syncPackages": false
  }
}
```

### Installed Packages

```coffee
# User
file-icons, v1.6.17
linter-csslint, v1.3.1
linter-htmlhint, v1.0.3
linter-js-yaml, v1.2.5
linter-jshint, v2.0.2
linter-php, v1.2.0
linter-phpcs, v1.3.1
linter-phpmd, v1.4.1
linter-scss-lint, v2.5.1
linter-tidy, v2.1.0
minimap, v4.19.0
nuclide, v0.120.0
sync-settings, v0.7.0
terminal-plus, v0.14.5

# Dev
No dev packages
```

![image](https://cloud.githubusercontent.com/assets/1218902/13677978/1e41705a-e6cb-11e5-8cd0-99db9a256752.png)

**Comment by dirk-thomas** [comment] 2016-03-10 17:24
Duplicate of #194.

In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Closed by dirk-thomas** 2016-03-10 17:24 UTC

**Comment by RVN-BR** [comment] 2016-03-10 17:28
damn! good catch... revoked it but thanks for pointing it out... the extension or atom should have a way of disabling/obfuscating some personal data... I didnt even realize it.. thankfully it was quickly brought to my attention! thanks @dirk-thomas
