### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/nvelickovic10/.atom/packages/sync...

### ISSUE THREAD

**Issue by nvelickovic10** [Hackafe/atom-sync-settings#210] opened 2016-03-08 13:38 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.7.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/nvelickovic10/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/nvelickovic10/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/Users/nvelickovic10/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/Users/nvelickovic10/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/Users/nvelickovic10/.atom/packages/sync-settings/lib/sync-settings.coffee:198:18)
    at Object.SyncSettings.checkForUpdate (/Users/nvelickovic10/.atom/packages/sync-settings/lib/sync-settings.coffee:46:8)
    at Immediate._onImmediate (/Users/nvelickovic10/.atom/packages/sync-settings/lib/sync-settings.coffee:32:8)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
     -9:10.9.0 application:add-project-folder (span.name.icon.icon-file-directory)
     -8:42.2.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
     -8:36.6.0 tabs:close-all-tabs (li.tab.sortable.right-clicked)
  6x -3:40.3.0 core:move-up (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:47.6.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-an-old-hope-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "symbols-view"
    ],
    "themes": [
      "one-dark-ui",
      "an-old-hope-syntax"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "53fa8ddf-80d8-447a-b0bf-2b8b8e04436c",
    "_lastBackupHash": "8167acc91be8c0c15152927837ad10fded83577d",
    "gistId": "f49bb9fe2cbb64c2efb8",
    "personalAccessToken": "efaae7038cecf09a6adb12d7b25c20c1a6d68d68"
  }
}
```

### Installed Packages

```coffee
# User
an-old-hope-syntax, v0.5.0
color-picker, v2.1.1
hyperclick, v0.0.35
js-hyperclick, v1.4.1
linter, v1.11.3
linter-eslint, v7.0.0
minimap, v4.20.0
open-in-browsers, v0.0.11
react, v0.14.1
sync-settings, v0.7.0

# Dev
No dev packages
```

**Comment by jerone** [comment] 2016-03-08 14:17
Duplicate of https://github.com/Hackafe/atom-sync-settings/issues/194.

In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Closed by jerone** 2016-03-08 14:17 UTC

**Comment by nvelickovic10** [comment] 2016-03-08 14:21
Thanks,

I didn't check autogenerated report before commiting it.

**Comment by jerone** [comment] 2016-03-08 14:43
> I didn't check autogenerated report before commiting it.

https://github.com/atom/notifications/pull/113
