### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/zander/.atom/packages/sync-settin...

### ISSUE THREAD

**Issue by AlexanderOtavka** [Hackafe/atom-sync-settings#215] opened 2016-03-08 18:22 UTC
[Enter steps to reproduce below:]

1. I updated the package, as soon as the update finished, this error was thrown.
2. It is also thrown every time I try to backup my settings.

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.7.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/zander/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/zander/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/Users/zander/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/Users/zander/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/Users/zander/.atom/packages/sync-settings/lib/sync-settings.coffee:198:18)
    at Object.SyncSettings.backup (/Users/zander/.atom/packages/sync-settings/lib/sync-settings.coffee:127:6)
    at atom-workspace.<anonymous> (/Users/zander/.atom/packages/sync-settings/lib/sync-settings.coffee:23:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1013:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```

### Commands

```
     -9:12.5.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-darkular-syntax.theme-native-ui)
 10x -1:11.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:50.2.0 markdown-preview:toggle (atom-text-editor.editor.is-focused)
     -0:01.3.0 sync-settings:backup (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "openEmptyEditorOnStart": false,
    "projectHome": "/Users/zander/Developer/GitHub",
    "themes": [
      "native-ui",
      "darkular-syntax"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "cb097b51-fe44-4cbd-abab-df3da877f60e",
    "_lastBackupHash": "c7a36bd1bac3bfe2ef3fd23b45f298b2dc1726ea",
    "gistId": "e54df4fa4462b977c4a5",
    "personalAccessToken": "55865c74f2fa8b9135579bee01525b7f1bdd436b"
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.5.1
auto-detect-indentation, v1.0.0
autoclose-html, v0.23.0
darkular-syntax, v0.3.0
highlight-selected, v0.11.2
language-gitignore, v0.2.0
linter, v1.11.3
linter-jscs, v3.4.8
linter-jshint, v2.0.2
minimap, v4.20.0
minimap-autohide, v0.10.1
minimap-highlight-selected, v4.4.0
minimap-linter, v1.1.1
native-ui, v0.17.0
sync-settings, v0.7.0

# Dev
No dev packages
```

**Comment by jerone** [comment] 2016-03-08 18:36
Duplicate of https://github.com/Hackafe/atom-sync-settings/issues/194.

In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Closed by jerone** 2016-03-08 18:36 UTC

**Comment by AlexanderOtavka** [comment] 2016-03-08 23:56
@jerone Thanks for letting me know about the personal access token; I just hit the create issue button on the error message without looking over it.  Token has been revoked.
