### ISSUE TITLE
Uncaught TypeError: Cannot read property 'deactivateKeymaps' of undefined

### ISSUE THREAD

**Issue by Kampfmoehre** [Hackafe/atom-sync-settings#132] opened 2015-09-29 06:57 UTC
Steps to reproduce:

1. Build Atom from Source
2. Install Sync-settings via apm
3. Enter Personal Access Token and Gist Id in Atom
4. Call Restore backup from command palette

**Atom Version**: 1.1.0-beta.0-ad60d7b
**System**: Linux Mint
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.6.0

### Stack Trace

Uncaught TypeError: Cannot read property 'deactivateKeymaps' of undefined

```
At /usr/local/share/atom/resources/app.asar/src/package-manager.js:339

TypeError: Cannot read property 'deactivateKeymaps' of undefined
  at /usr/local/share/atom/resources/app.asar/src/package-manager.js:339:50
  at /usr/local/share/atom/resources/app.asar/src/config.js:587:20
  at Emitter.module.exports.Emitter.emit (/usr/local/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (/usr/local/share/atom/resources/app.asar/src/config.js:772:29)
  at Config.module.exports.Config.setRawValue (/usr/local/share/atom/resources/app.asar/src/config.js:564:19)
  at Config.module.exports.Config.set (/usr/local/share/atom/resources/app.asar/src/config.js:233:14)
  at Object.SyncSettings.applySettings (/home/sissmer/.atom/packages/sync-settings/lib/sync-settings.coffee:219:21)
  at Object.SyncSettings.applySettings (/home/sissmer/.atom/packages/sync-settings/lib/sync-settings.coffee:216:10)
  at /home/sissmer/.atom/packages/sync-settings/lib/sync-settings.coffee:168:14
  at /home/sissmer/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/gists.js:342:17
  at callCallback (/home/sissmer/.atom/packages/sync-settings/node_modules/github/index.js:743:17)
  at IncomingMessage.<anonymous> (/home/sissmer/.atom/packages/sync-settings/node_modules/github/index.js:796:25)
  at emitNone (events.js:72:20)
  at IncomingMessage.emit (events.js:166:7)
  at endReadableNT (_stream_readable.js:889:12)
  at doNTCallback2 (node.js:438:9)
  at process._tickCallback (node.js:352:17)

```

### Commands

```
     -0:43 settings-view:open (atom-text-editor.editor.is-focused)
  2x -0:31.6.0 core:paste (atom-text-editor#sync-settings.personalAccessToken.editor.mini.is-focused)
     -0:11.6.0 command-palette:toggle (div.settings-view.pane-item)
     -0:09.2.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:08.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:08.5.0 sync-settings:restore (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".php.html",
      ".git",
      "coverage",
      "tags",
      "composer.*",
      ".tags_swap"
    ],
    "themes": [
      "atom-material-ui",
      "afterglow-like"
    ],
    "disabledPackages": [
      "autosave"
    ],
    "packagesWithKeymapsDisabled": [
      "atom-beautify"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "...",
    "personalAccessToken": "...",
    "gistId": "..."
  }
}
```

### Installed Packages

```coffee
# User
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by jonatasleon** [comment] 2015-11-17 11:49
Same here

Steps to reproduce:

1. Install Atom from .exe
2. Install Sync Settings from Atom Packages Install
3. Enter Personal Access Token and Gist Id in Atom
4. After syncing the settings on another system (In my case, an Atom version installed on Ubuntu 14.04), open the Atom and call Restore backup from command palette

**Atom Version**: 1.1.0
**System**: Windows 10 Pro
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.6.0


### Stack Trace

Uncaught TypeError: Cannot read property 'deactivateKeymaps' of undefined

```
At C:\Users\jonatas\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package-manager.js:335

TypeError: Cannot read property 'deactivateKeymaps' of undefined
    at C:\Users\jonatas\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package-manager.js:335:50
    at C:\Users\jonatas\AppData\Local\atom\app-1.1.0\resources\app.asar\src\config.js:568:20
    at Emitter.module.exports.Emitter.emit (C:\Users\jonatas\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at Config.module.exports.Config.emitChangeEvent (C:\Users\jonatas\AppData\Local\atom\app-1.1.0\resources\app.asar\src\config.js:753:29)
    at Config.module.exports.Config.setRawValue (C:\Users\jonatas\AppData\Local\atom\app-1.1.0\resources\app.asar\src\config.js:545:19)
    at Config.module.exports.Config.set (C:\Users\jonatas\AppData\Local\atom\app-1.1.0\resources\app.asar\src\config.js:215:14)
    at Object.SyncSettings.applySettings (C:\Users\jonatas\.atom\packages\sync-settings\lib\sync-settings.coffee:219:21)
    at Object.SyncSettings.applySettings (C:\Users\jonatas\.atom\packages\sync-settings\lib\sync-settings.coffee:216:10)
    at C:\Users\jonatas\.atom\packages\sync-settings\lib\sync-settings.coffee:168:14
    at C:\Users\jonatas\.atom\packages\sync-settings\node_modules\github\api\v3.0.0\gists.js:342:17
```

### Commands

```
     -0:38.4.0 sync-settings:restore (atom-workspace.workspace.scrollbars-visible-always.theme-hydra-syntax-theme.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "hydra-syntax-theme"
    ],
    "autoHideMenuBar": true,
    "packagesWithKeymapsDisabled": [
      "zentabs",
      "an-color-picker"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "0d8c9082-2d2c-42a3-b6bd-c7ba512e5ad8",
    "personalAccessToken": "40d15518dfdec7ba360a83f3783da2689cc568c8",
    "gistId": "eb9e87e9d6b030c14313",
    "_lastBackupHash": "0ccd32f046d5193fe208fd85bf14880b362b6646"
  }
}
```

### Installed Packages

```coffee
# User
atom-django, v0.3.0
autocomplete-paths, v1.0.2
color-picker, v2.0.13
django-templates, v0.5.0
emmet, v2.3.14
file-icons, v1.6.11
formatter, v2.12.3
hydra-syntax-theme, v0.2.4
language-aspx, v0.4.0
linter, v1.10.0
linter-eslint, v4.0.0
local-history, v3.2.3
minimap, v4.16.0
pigments, v0.18.1
project-manager, v2.6.5
set-syntax, v0.3.0
sync-settings, v0.6.0
travis-ci-status, v0.18.0

# Dev
No dev packages
```

**Comment by dirk-thomas** [comment] 2016-01-13 17:15
I can't reproduce this. Can anybody? Is the same problem still happening for you? Have you tried using newer versions of Atom?

The not found property `deactivateKeymaps` is not being used anywhere in this package. Therefore I am inclined to close this ticket.

**Comment by Kampfmoehre** [comment] 2016-01-13 17:19
This problem did not occur since I posted this, you can close the issue if you want.

**Comment by dirk-thomas** [comment] 2016-02-09 18:09
@jonatasleon In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Comment by dirk-thomas** [comment] 2016-02-09 18:09
I will close this for now. If it happens again please comment here and it can be reopened.

**Closed by dirk-thomas** 2016-02-09 18:09 UTC
