### ISSUE TITLE
Uncaught Error: OAuth2 authentication requires a token or key 

### ISSUE THREAD

**Issue by puxoskii** [Hackafe/atom-sync-settings#148] opened 2015-11-26 15:50 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Unknown Windows Version
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.6.0

### Stack Trace

Uncaught Error: OAuth2 authentication requires a token or key

**Comment by dirk-thomas** [comment] 2016-01-13 16:35
Duplicate of #147. Closing.

**Closed by dirk-thomas** 2016-01-13 16:35 UTC
