### ISSUE TITLE
Disabled packages are synced and activated

### ISSUE THREAD

**Issue by Zorgatone** [Hackafe/atom-sync-settings#188] opened 2016-03-03 09:30 UTC
When I sync a new atom installation, all the packages are synced and installed as expected.

The only thing that bothers me is that they're all active, even the one that I have disabled on other computers (because they drop my PC performance a lot, and I activate them only when needed. i.e. atom-typescript)

**Comment by dirk-thomas** [comment] 2016-03-05 07:06
Duplicate of #92.

**Closed by dirk-thomas** 2016-03-05 07:06 UTC
Labels: duplicate
