### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/home/javierjmx/.atom/packages/sync-sett...

### ISSUE THREAD

**Issue by javierjmx** [Hackafe/atom-sync-settings#226] opened 2016-03-09 16:12 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Ubuntu 14.04.4
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.7.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/home/javierjmx/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/home/javierjmx/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/home/javierjmx/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/home/javierjmx/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/home/javierjmx/.atom/packages/sync-settings/lib/sync-settings.coffee:198:18)
    at Object.SyncSettings.checkForUpdate (/home/javierjmx/.atom/packages/sync-settings/lib/sync-settings.coffee:46:8)
    at Immediate._onImmediate (/home/javierjmx/.atom/packages/sync-settings/lib/sync-settings.coffee:32:8)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
     -1:52.1.0 sync-settings:restore (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:41.9.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:01.5.0 tree-view:remove-project-folder (span.name.icon.icon-repo)
     -0:58.2.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {},
  "sync-settings": {
    "_analyticsUserId": "7a9f45f1-d2fa-45a1-84e6-b82b077d47f6",
    "_lastBackupHash": "4b9f03ee9bc69e781526fffc5313f7f85029144a",
    "gistId": "b28cd16485e090662a63",
    "personalAccessToken": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.13.2
autocomplete-modules, v1.4.1
editorconfig, v1.2.4
linter, v1.11.3
linter-eslint, v7.0.0
linter-flow, v4.1.0
sync-settings, v0.7.0
term3, v0.21.2

# Dev
No dev packages
```

**Comment by dirk-thomas** [comment] 2016-03-09 16:46
Duplicate of #194.

In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Closed by dirk-thomas** 2016-03-09 16:46 UTC
