### ISSUE TITLE
Environment-dependent settings

### ISSUE THREAD

**Issue by konradedgar** [Hackafe/atom-sync-settings#168] opened 2016-01-14 16:48 UTC
Hi,
I use Atom at work (Windows) and at home (Mac OS X). I would like to be able to distinguish between those environments and load elements of configuration depending on the environment. In the context of this particular challenge the functionality allowing for differentiating between various OS would be enough. For example, I could then choose to load certain themes and colour for Windows environment and apply another set of settings for home.

**Comment by dirk-thomas** [comment] 2016-03-05 07:33
Duplicate of the discussion in #159.

**Closed by dirk-thomas** 2016-03-05 07:33 UTC
Labels: duplicate
